// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2qUqCgE4hP8HlGtKdiMXACMCCbLUPH7o',
    appId: '1:1077007716902:web:4bc0f229b1811d08048ce7',
    messagingSenderId: '1077007716902',
    projectId: 'flow-22824',
    authDomain: 'flow-22824.firebaseapp.com',
    storageBucket: 'flow-22824.firebasestorage.app',
    measurementId: 'G-H0ML6R3QV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7yF-Bry_TO0qhdxPERZZ6isCc67er6q8',
    appId: '1:1077007716902:android:e6adf5937409707a048ce7',
    messagingSenderId: '1077007716902',
    projectId: 'flow-22824',
    storageBucket: 'flow-22824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzS3QyJ40M-spLshgJDcimUQ9q95DeMn8',
    appId: '1:1077007716902:ios:c495dc1ac2ed1379048ce7',
    messagingSenderId: '1077007716902',
    projectId: 'flow-22824',
    storageBucket: 'flow-22824.firebasestorage.app',
    iosBundleId: 'com.flow.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzS3QyJ40M-spLshgJDcimUQ9q95DeMn8',
    appId: '1:1077007716902:ios:c495dc1ac2ed1379048ce7',
    messagingSenderId: '1077007716902',
    projectId: 'flow-22824',
    storageBucket: 'flow-22824.firebasestorage.app',
    iosBundleId: 'com.flow.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2qUqCgE4hP8HlGtKdiMXACMCCbLUPH7o',
    appId: '1:1077007716902:web:b3459c876881a05b048ce7',
    messagingSenderId: '1077007716902',
    projectId: 'flow-22824',
    authDomain: 'flow-22824.firebaseapp.com',
    storageBucket: 'flow-22824.firebasestorage.app',
    measurementId: 'G-34R825E3TW',
  );

}